

Welcome:
  message: Hey Welcome to Ecom-cataLoG_🛒

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EcomCataLog
    username: root
    password: Root@#123_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#E-commerce Product Catalog:
#● Objective: Build a Java application for managing an e-commerce product
#  catalog.
#● Details: Key entities are Product and Category. Each product belongs to
#  one category, but a category can have many products.
#● Relationships: OneToMany between Category and Product.
#● Tasks: Develop functionalities to add new products under categories,
#  update product details, remove products, and list all products under a
#  specific category.


